---
- name: Setup web servers
  hosts: web-servers
  become: yes
  remote_user: "{{ new_admin_user }}"
  roles:
    - ssh
    - node_exporter
    - cloudflare
    - letsencrypt
    - nginx
    - portfolio
    - nginx_exporter
